//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApplication2.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Auction Not sold:&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;auction/Username&quot;/&gt;
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		Your aution item &lt;xsl:value-of select=&quot;auction/item/Name&quot; /&gt; was not sold.
        ///	&lt;/p&gt;
        ///	&lt;br /&gt;&lt;br/&gt;
        ///	Thank you for using or site.	
        ///	&lt;/BODY&gt;
        ///	&lt;/HTML&gt;
        ///	&lt;/xsl:template&gt;
        ///&lt;/xsl:stylesheet&gt;.
        /// </summary>
        internal static string Auction_NotSold_Email_Body {
            get {
                return ResourceManager.GetString("Auction.NotSold.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Offer Accepted :&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;auction/Bidder&quot;/&gt;
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		Congratulations, you offer on &lt;xsl:value-of select=&quot;auction/item/Name&quot;/&gt; item is accepted
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		We will inform you once the shipment is ready.
        ///	&lt;/p&gt;
        ///	&lt;br /&gt;&lt;br/&gt;
        ///	Thank you for using or site.	
        ///	&lt;/BODY&gt;
        ///	&lt;/HTML&gt;
        ///	&lt;/xsl:template&gt;
        ///&lt;/xsl:stylesheet&gt;.
        /// </summary>
        internal static string Auction_Offer_Accepted_Email_Body {
            get {
                return ResourceManager.GetString("Auction.Offer.Accepted.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Offer Offered :&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;auction/Bidder&quot;/&gt;
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		There is a new offer on the item &lt;xsl:value-of select=&quot;auction/item/Name&quot;/&gt; for &lt;xsl:value-of select=&quot;auction/AuctionAmount&quot; /&gt; amount.
        ///	&lt;/p&gt;
        ///	&lt;br /&gt;&lt;br/&gt;
        ///	Thank you for using or site.	
        ///	&lt;/BODY&gt;
        ///	&lt;/HTML&gt;
        ///	&lt;/xsl:template&gt;
        ///&lt;/xsl:stylesheet&gt;.
        /// </summary>
        internal static string Auction_Offer_Offered_Email_Body {
            get {
                return ResourceManager.GetString("Auction.Offer.Offered.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Offer Rejected :&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;auction/Bidder&quot;/&gt;
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		Your current offer on item &lt;xsl:value-of select=&quot;auction/item/Name&quot;/&gt; for &lt;xsl:value-of select=&quot;auction/AuctionAmount&quot; /&gt; amount was rejected. Please login into the website to increase the amount.
        ///	&lt;/p&gt;
        ///	&lt;br/&gt;
        ///	Thank you for using or site.	
        ///	&lt;/BODY&gt;
        ///	&lt;/HTML&gt;
        ///	&lt;/xsl:template&gt;
        ///&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Auction_Offer_Rejected_Email_Body {
            get {
                return ResourceManager.GetString("Auction.Offer.Rejected.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Auction Outbid:&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;auction/Bidder&quot;/&gt;
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		You are out bid on the aution item &lt;xsl:value-of select=&quot;auction/item/Name&quot; /&gt;. 
        ///		&lt;!--	Set a variable to hold the href link --&gt;
        ///		&lt;xsl:variable name=&quot;href&quot; select=&quot;aution/item/imagepath&quot;&gt;&lt;/xsl:variable&gt;
        ///		&lt;!--  Put the contents of the variable into the HTML --&gt;		
        ///		&lt;img src=&quot;{$hre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Auction_Outbid_Email_Body {
            get {
                return ResourceManager.GetString("Auction.Outbid.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Auction Question:&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;auction/Username&quot;/&gt;
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		 There is a question from &lt;xsl:value-of select=&quot;auction/Bidder&quot;/&gt; for &lt;xsl:value-of select=&quot;auction/item/Name&quot; /&gt; item. 
        ///		 &lt;br/&gt;&lt;br/&gt;
        ///		 &lt;xsl:value-of select=&quot;auction/Question&quot; /&gt; ?
        ///	&lt;/p&gt;
        ///	&lt;br /&gt;&lt;br/&gt;
        ///	Thank you for using or site.	
        ///	&lt;/BODY&gt;
        ///	&lt;/HTML&gt;
        ///	&lt;/xsl:template&gt;
        ///&lt;/xsl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Auction_Question_Email_Body {
            get {
                return ResourceManager.GetString("Auction.Question.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Auction Remainder:&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;auction/Bidder&quot;/&gt;
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		Please make a payment on the &lt;xsl:value-of select=&quot;auction/item/Name&quot; /&gt; item that you won in the auction.. 
        ///		&lt;br/&gt;&lt;br/&gt;
        ///		Please take an action.
        ///	&lt;/p&gt;
        ///	&lt;br /&gt;&lt;br/&gt;
        ///	Thank you for using or site.	
        ///	&lt;/BODY&gt;
        ///	&lt;/HTML&gt;
        ///	&lt;/xsl:template&gt;
        ///&lt;/xsl:stylesheet&gt;.
        /// </summary>
        internal static string Auction_Reminder_Email_Body {
            get {
                return ResourceManager.GetString("Auction.Reminder.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Auction Repost:&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;auction/Username&quot;/&gt;
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		Please repost your item &lt;xsl:value-of select=&quot;auction/item/Name&quot; /&gt;. Your auction was expired.
        ///		&lt;br/&gt;&lt;br/&gt;
        ///		Please take an action.
        ///	&lt;/p&gt;
        ///	&lt;br /&gt;&lt;br/&gt;
        ///	Thank you for using or site.	
        ///	&lt;/BODY&gt;
        ///	&lt;/HTML&gt;
        ///	&lt;/xsl:template&gt;
        ///&lt;/xsl:stylesheet&gt;.
        /// </summary>
        internal static string Auction_Repost_Email_Body {
            get {
                return ResourceManager.GetString("Auction.Repost.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Auction Won :&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;auction/Bidder&quot;/&gt;
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		Congratulations, you have won the auction of &lt;xsl:value-of select=&quot;auction/item/Name&quot;/&gt; item for &lt;xsl:value-of select=&quot;auction/AuctionAmount&quot;/&gt;.
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		We will inform you of any further steps.
        ///	&lt;/p&gt;
        ///	&lt;br /&gt;&lt;br/&gt;
        ///	Thank you for using or site.	
        ///	&lt;/BODY&gt;
        ///	&lt;/HTML&gt;
        ///	&lt;/xsl:tem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Auction_Sold_Bidder_Email_Body {
            get {
                return ResourceManager.GetString("Auction.Sold.Bidder.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Auction Item Sold :&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;auction/Username&quot;/&gt;
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		Congratulations, the auction of &lt;xsl:value-of select=&quot;auction/item/Name&quot;/&gt; item is completed and the the bidder &lt;xsl:value-of select=&quot;auction/Bidder&quot;/&gt; has won for &lt;xsl:value-of select=&quot;auction/AuctionAmount&quot;/&gt; price.
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		Please login into the our website and comple [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Auction_Sold_Seller_Email_Body {
            get {
                return ResourceManager.GetString("Auction.Sold.Seller.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Auction Repost:&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;auction/Bidder&quot;/&gt;
        ///		&lt;br /&gt;&lt;br/&gt;
        ///		The item &lt;xsl:value-of select=&quot;auction/item/Name&quot; /&gt; is reposted. Please check this item in you are still interested.		     
        ///		
        ///	&lt;/p&gt;
        ///	&lt;br /&gt;&lt;br/&gt;
        ///	Thank you for using or site.	
        ///	&lt;/BODY&gt;
        ///	&lt;/HTML&gt;
        ///	&lt;/xsl:template&gt;
        ///&lt;/xsl:stylesheet&gt;.
        /// </summary>
        internal static string Auction_WatcherRepost_Email_Body {
            get {
                return ResourceManager.GetString("Auction.WatcherRepost.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Item Shipped :&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;order/Username&quot;/&gt;
        ///		&lt;br/&gt;
        ///		Order ID: &lt;xsl:value-of select=&quot;order/OrderNumber&quot;/&gt;
        ///	&lt;/p&gt;
        ///	&lt;!--	Set a variable to hold the href link --&gt;
        ///	&lt;xsl:variable name=&quot;href&quot; select=&quot;/order/shipment/url&quot;&gt;&lt;/xsl:variable&gt;
        ///	&lt;!--  Put the contents of the variable into the HTML --&gt;
        ///    Your order has been shipped. Please click on the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemShipped_Email_Body {
            get {
                return ResourceManager.GetString("ItemShipped.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Payment Info Created :&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;payment/Username&quot;/&gt;
        ///		&lt;br/&gt;
        ///		A new payment info has been created. A new &lt;xsl:value-of select=&quot;payment/CardType&quot;/&gt; card with card number &lt;xsl:value-of select=&quot;payment/last4CardNumber&quot;/&gt; has been added.
        ///	&lt;/p&gt;
        ///		If you have not done this activity, please call our customer service about it at 1-800-xxx-xxxx
        ///	&lt;br [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PaymentInfo_Created_Email_Body {
            get {
                return ResourceManager.GetString("PaymentInfo.Created.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Payment Info deleted :&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;payment/Username&quot;/&gt;
        ///		&lt;br/&gt;
        ///		An existing &lt;xsl:value-of select=&quot;payment/CardType&quot;/&gt; card with card number &lt;xsl:value-of select=&quot;payment/last4CardNumber&quot;/&gt; has been deleted.
        ///	&lt;/p&gt;
        ///		If you have not done this activity, please call our customer service about it at 1-800-xxx-xxxx
        ///	&lt;br /&gt;&lt;br/&gt;
        ///	Thank you for usin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PaymentInfo_Deleted_Email_Body {
            get {
                return ResourceManager.GetString("PaymentInfo.Deleted.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Payment Info Updated :&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;payment/Username&quot;/&gt;
        ///		&lt;br/&gt;
        ///		Payment info has been updated. An existing &lt;xsl:value-of select=&quot;payment/CardType&quot;/&gt; card with card number &lt;xsl:value-of select=&quot;payment/last4CardNumber&quot;/&gt; has been updated.
        ///	&lt;/p&gt;
        ///		If you have not done this activity, please call our customer service about it at 1-800-xxx-xxxx
        ///	&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PaymentInfo_Updated_Email_Body {
            get {
                return ResourceManager.GetString("PaymentInfo.Updated.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Payment Reminder:&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;PaymentReminder/Username&quot;/&gt;
        ///		&lt;br/&gt;&lt;br/&gt;
        ///		This is a friendly reminder that the following invoice is overdue&lt;br/&gt;
        ///	&lt;/p&gt;
        ///			&lt;TABLE Border=&quot;0&quot;&gt;			
        ///			&lt;TR&gt;
        ///				&lt;td&gt;Invoice Date:  &lt;/td&gt;
        ///				&lt;td&gt;&lt;xsl:value-of select=&quot;PaymentReminder/invoice/InvoiceDate&quot;/&gt;&lt;/td&gt;
        ///			&lt;/TR&gt;
        ///			&lt;TR&gt;
        ///				&lt;td&gt;Invoice No:  &lt;/td&gt;
        ///				&lt;td&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PaymentReminder_Email_Body {
            get {
                return ResourceManager.GetString("PaymentReminder.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H2&gt;Shipment Reminder:&lt;/H2&gt;		
        ///	&lt;p&gt;
        ///		Dear &lt;xsl:value-of select=&quot;ShipmentReminder/Username&quot;/&gt;
        ///		&lt;br/&gt;
        ///		Order ID: &lt;xsl:value-of select=&quot;ShipmentReminder/order/OrderNumber&quot;/&gt;
        ///	&lt;/p&gt;
        ///    Your Marketplace sale is official! We&apos;ve deposited your earnings from the sale of this item into your Payments account.
        ///
        ///	Please ship the item immediately via &lt;xsl:value-of select=&quot;ShipmentRemin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShipNowReminder_Email_Body {
            get {
                return ResourceManager.GetString("ShipNowReminder.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///	&lt;HTML&gt;
        ///	&lt;BODY&gt;
        ///	&lt;H1&gt;Books:&lt;/H1&gt;
        ///		&lt;xsl:apply-templates/&gt;
        ///	&lt;/BODY&gt;
        ///	&lt;/HTML&gt;
        ///	&lt;/xsl:template&gt;
        ///
        ///	&lt;xsl:template match=&quot;bookstore&quot;&gt;
        ///	&lt;!-- Prices and books --&gt;
        ///		&lt;TABLE Border=&quot;1&quot;&gt;
        ///		&lt;TH&gt;Title&lt;/TH&gt;
        ///		&lt;TH&gt;ISBN&lt;/TH&gt;
        ///		&lt;TH&gt;Price&lt;/TH&gt;
        ///			&lt;xsl:apply-templates select=&quot;book&quot;/&gt;
        ///		&lt;/TABLE&gt;
        ///	&lt;/xsl:template&gt;
        ///
        ///	&lt;xsl:template match=&quot;book&quot;&gt;
        ///		&lt;TR&gt;
        ///			&lt;TD&gt;&lt;xsl:apply-templates select=&quot;title&quot;/&gt;&lt;/TD&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XsltContent {
            get {
                return ResourceManager.GetString("XsltContent", resourceCulture);
            }
        }
    }
}
